local ChatLists = {
    greetTable = {
      "hi",
      "hello",
      "greetings",
      "bonjour",
      "hola",
      "hey",
    },
    introTable = {
      "you look really cool",
      "hows life",
      "im such a big fan i watched your FaceBook Live",
      "are you a funny person",
      "plz dont be mean u look egotistical",
      "dont ask me to do b4b. thats the most dollhousian thing you nd your kind does",
      "i know ur the type to eat cheeseburgers unethically",
      "you look like you extort femalic females i wont be next",
      "i hope your house blows up bruh",
      "maybe you might get lucky and ill add you",
      "brooo wth is that outfit you look atrocious",
      "zoo weee mama",
      "Hi Hi Hi Hi Hi Hi Hi Hi Hi Hi Hi Hi Hi Hi",
      "dress coded now what BUDDY",
    },
    convoTable = {
      "havent been on krd or nun i deleted ts",
      "im a irl warrior now not a dollhousian bro",
      "i got bored nd just wanted to check out the new game",
      "where u been at man the outside world is crazy brah",
      "dude i got robbed yesterday by a homeless guy",
      "my eyeballs pink nd my feet brown bruh life aint the same no more",
      "can u tell me a joke nvm dont bruh i said it inna same sentence",
      "please spare me im bored",
      "i hate you because out of the 100 random messages u received dis 1",
      "dude i just wanna lay down but idrc",
      "HILLMURDER SONGS R SO HARDDD",
      "the underground rapping community is so cool but toxic dey kicked me off",
      "hey gurlie pop how u doin"
    },
    songTable = {
      "hillmurder - nine w/ @s6erpent #xp",
      "iraq radio mix pt 4",
      "hillmurder - invalidate",
      "len333 - shoot",
      "lunachrist - titans w/ kumosai",
      "ambi - play it out prod yk",
      "entity - WHY B SO SRS!?!?",
      "vnmpire - glamstar",
      "kursses - lait romani - what u see",
      "cyberia - play pretend",
      "textkill - goner (rare)",
      "ztarnm - you can do whatever",
      "ztarnm - i don't wanna do it",
      "sephe - wait...",
      "(dj slur) why would i lie",
      "bloody! x cap - stumpy and cheese",
      "feud - sight ft entity, lxght, naomi's grave and murderjj (deathrow)",
      "zinoblade - chaos emeralds // rouge (gemcalibur & wavebird)",
      "star67 - zombiekiller",
      "rachyl - bad game 2",
      "duwap kain - santa",
      "star67 - #ghoul",
      "pinkblxxd x star67 - untilted (rare)",
      "rachyl - oxy",
      "bloody! - alignment",
      "emiii - buford freestyle (rare)",
      "eddyoetty - growup",
      "onlinegraves - wrong turn",
      "islurwhenitalk - fed up",
      "bloody! - i like money",
      "hillmurder - ion fold #xp",
      "yuuki - night fall plague (rare)",
      "ksuuvi - at the backhouse",
      "korosu #k2 - deadline",
      "sublimits - geeked out my mind",
      "tenkay - never put my faith in her",
      "katai - da feelinn",
      "lust - Requiem For A Dream",
      "solar - Depressed and Fly",
      "luci4 - SHOW IT/SHE WANNA",
      "*67 - lov u like a razor",
      "lucifer - SOULFUL *REMIX*",
      "kursses - LAIT! #fantasia",
      "forevermore - my words never heard"
    },
    FriendlyOffer = {
      "maybe we can play a game some day when im online.",
      "ill probably join you on roblox.",
      "gotta be nice around here",
      "im dying for a friend right now"
    }
}
